# Generated by Django 6.0.3 on 2026-03-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remove_bg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
